"""add password for user

Revision ID: 0935fa0c518c
Revises: 8ef90253a386
Create Date: 2023-02-18 11:58:20.668113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0935fa0c518c'
down_revision = '8ef90253a386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
