"""add password for user V2

Revision ID: 19c8cb788437
Revises: 0935fa0c518c
Create Date: 2023-02-18 12:10:26.592973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c8cb788437'
down_revision = '0935fa0c518c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('salt', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
