"""change product description type V2

Revision ID: 2c6c6080c58f
Revises: 9c9a2a8beee3
Create Date: 2023-03-01 17:36:54.323440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6c6080c58f'
down_revision = '9c9a2a8beee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
