"""add is_admin parametr for user

Revision ID: 39caa24eaf6e
Revises: 449f111071cc
Create Date: 2023-02-15 00:40:01.995049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39caa24eaf6e'
down_revision = '449f111071cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
