"""add not null for columns in goods

Revision ID: 417f13102588
Revises: bd432d7267ee
Create Date: 2023-02-28 17:09:10.320095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417f13102588'
down_revision = 'bd432d7267ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'manufacture_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goods', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goods', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('goods', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('goods', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('goods', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('goods', 'manufacture_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
