"""add product description

Revision ID: 577e16533e95
Revises: 766c2a7e2326
Create Date: 2023-03-01 17:37:59.466789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577e16533e95'
down_revision = '766c2a7e2326'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'description')
    # ### end Alembic commands ###
