"""add goods and reviews

Revision ID: 6ea7ddde1d23
Revises: 39caa24eaf6e
Create Date: 2023-02-15 00:57:26.602656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea7ddde1d23'
down_revision = '39caa24eaf6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
