"""add links in table

Revision ID: 916d663e0ddf
Revises: 72e8d3acfc42
Create Date: 2023-02-28 17:40:37.076331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916d663e0ddf'
down_revision = '72e8d3acfc42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('manufacture_id', sa.Integer(), nullable=True))
    op.drop_constraint('goods_code_key', 'goods', type_='unique')
    op.create_foreign_key(None, 'goods', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'goods', 'manufactures', ['manufacture_id'], ['id'])
    op.drop_column('goods', 'manufacture_name')
    op.drop_column('goods', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('goods', sa.Column('manufacture_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.create_unique_constraint('goods_code_key', 'goods', ['code'])
    op.drop_column('goods', 'manufacture_id')
    op.drop_column('goods', 'category_id')
    # ### end Alembic commands ###
