"""change product description type

Revision ID: 9c9a2a8beee3
Revises: e200df7a34a2
Create Date: 2023-03-01 17:30:24.947045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9a2a8beee3'
down_revision = 'e200df7a34a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
