"""add stars for goods reviews and change goods code length

Revision ID: b47a379f2402
Revises: 36ee144c0e25
Create Date: 2023-02-15 01:27:20.012067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47a379f2402'
down_revision = '36ee144c0e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('stars_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'stars_count')
    # ### end Alembic commands ###
