"""move unique and add manufacture

Revision ID: bd432d7267ee
Revises: b635dcb1dafb
Create Date: 2023-02-28 16:25:32.930767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd432d7267ee'
down_revision = 'b635dcb1dafb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('manufacture_name', sa.String(), nullable=True))
    op.drop_constraint('goods_name_key', 'goods', type_='unique')
    op.create_unique_constraint(None, 'goods', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    op.create_unique_constraint('goods_name_key', 'goods', ['name'])
    op.drop_column('goods', 'manufacture_name')
    # ### end Alembic commands ###
