"""add not null in products

Revision ID: c960ee340a91
Revises: 916d663e0ddf
Create Date: 2023-02-28 17:41:30.739423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c960ee340a91'
down_revision = '916d663e0ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goods', 'manufacture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods', 'manufacture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goods', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
