"""add unique manufacture, category name

Revision ID: ce722104fe34
Revises: c960ee340a91
Create Date: 2023-02-28 18:11:45.902407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce722104fe34'
down_revision = 'c960ee340a91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'manufactures', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufactures', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
