version: "3.3"
services:
  apple_devices_nginx:
    container_name: apple_devices_web
    build:
      context: "."
      dockerfile: "nginx/Dockerfile"
    ports:
      - "564:80"
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../backend/src/pictures:/var/www/AppleDevices.xahprod.ru/public/pictures
  apple_devices_api:
    container_name: apple_devices_api
    build:
      context: "../"
      dockerfile: "Docker/backend/Dockerfile"
